version: "3.9"

services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  producer_service:
    build:
      context: ./producer
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis

  consumer_service:
    build:
      context: ./consumer
    depends_on:
      - redis
      - flask_app
    environment:
      - REDIS_HOST=redis

  flask_app:
    build:
      context: ../my_flask_project
    ports:
      - "5000:5000"

  fastapi_app:
    build:
      context: ../my_fastapi_project
    ports:
      - "8000:8000"
