version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      - FLASK_APP=app
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
